InfnetMovieDataBaseEntity/Models/ErrorViewModel.cs
using System;

namespace InfnetMovieDataBaseEntity.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InfnetMovieDataBaseEntity/Controllers/FilmesController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InfnetMovieDataBaseEntity.Domain;

namespace InfnetMovieDataBaseEntity.Controllers
{
    public class FilmesController : Controller
    {
        private readonly MovieEntityDb _context;

        public FilmesController(MovieEntityDb context)
        {
            _context = context;
        }

        // GET: Filmes
        public async Task<IActionResult> Index()
        {
            var movieEntityDb = _context.Filmes.Include(f => f.Genero);
            return View(await movieEntityDb.ToListAsync());
        }

        public IActionResult List(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            IQueryable<Filme> filme = _context.Filmes
                .Include(f => f.Genero)
                .Where(m => m.GeneroId == id);

            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // GET: Filmes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filmes
                .Include(f => f.Genero)
               .FirstOrDefaultAsync(m => m.FilmeId == id);
            if (filme == null)
            { 
                return NotFound();
            }

            return View(filme);
        }

        // GET: Filmes/Create
        public IActionResult Create()
        {
            ViewData["GeneroId"] = new SelectList(_context.Generos, "GeneroId", "GeneroId");
            return View();
        }

        // POST: Filmes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FilmeId,Titulo,TituloOriginal,Ano,GeneroId")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Generos, "GeneroId", "GeneroId", filme.GeneroId);
            return View(filme);
        }

        // GET: Filmes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filmes.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }
            ViewData["GeneroId"] = new SelectList(_context.Generos, "GeneroId", "GeneroId", filme.GeneroId);
            return View(filme);
        }

        // POST: Filmes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FilmeId,Titulo,TituloOriginal,Ano,GeneroId")] Filme filme)
        {
            if (id != filme.FilmeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.FilmeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Generos, "GeneroId", "GeneroId", filme.GeneroId);
            return View(filme);
        }

        // GET: Filmes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filmes
                .Include(f => f.Genero)
                .FirstOrDefaultAsync(m => m.FilmeId == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // POST: Filmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filme = await _context.Filmes.FindAsync(id);
            _context.Filmes.Remove(filme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id)
        {
            return _context.Filmes.Any(e => e.FilmeId == id);
        }
    }
}

InfnetMovieDataBaseEntity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using InfnetMovieDataBaseEntity.Models;

namespace InfnetMovieDataBaseEntity.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InfnetMovieDataBaseEntity/Views/Filmes/Create.cshtml
@model InfnetMovieDataBaseEntity.Domain.Filme

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TituloOriginal" class="control-label"></label>
                <input asp-for="TituloOriginal" class="form-control" />
                <span asp-validation-for="TituloOriginal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class ="form-control" asp-items="ViewBag.GeneroId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfnetMovieDataBaseEntity/Views/Filmes/Delete.cshtml
@model InfnetMovieDataBaseEntity.Domain.Filme

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TituloOriginal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TituloOriginal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.GeneroId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InfnetMovieDataBaseEntity/Views/Filmes/Details.cshtml
@model InfnetMovieDataBaseEntity.Domain.Filme

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Filme</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TituloOriginal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TituloOriginal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.GeneroId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.FilmeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InfnetMovieDataBaseEntity/Views/Filmes/Edit.cshtml
@model InfnetMovieDataBaseEntity.Domain.Filme

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Filme</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FilmeId" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TituloOriginal" class="control-label"></label>
                <input asp-for="TituloOriginal" class="form-control" />
                <span asp-validation-for="TituloOriginal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class="form-control" asp-items="ViewBag.GeneroId"></select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InfnetMovieDataBaseEntity/Views/Filmes/Index.cshtml
@model IEnumerable<InfnetMovieDataBaseEntity.Domain.Filme>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TituloOriginal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TituloOriginal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero.GeneroId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FilmeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FilmeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FilmeId">Delete</a> |
                <a asp-action="List" asp-route-id="@item.GeneroId">FilmesDoMesmoGenero</a> 
            </td>
        </tr>
}
    </tbody>
</table>

InfnetMovieDataBaseEntity/Views/Filmes/List.cshtml
@model IEnumerable<InfnetMovieDataBaseEntity.Domain.Filme>

@{
    ViewData["Title"] = "List";
}

<h1>FilmesDoMesmoGenero</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TituloOriginal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TituloOriginal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ano)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero.GeneroId)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.FilmeId">Details</a> 
            </td>
        </tr>
}
    </tbody>
</table>

InfnetMovieDataBaseEntity/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InfnetMovieDataBaseEntity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InfnetMovieDataBaseEntity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InfnetMovieDataBaseEntity</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes" asp-action="Index">Filmes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InfnetMovieDataBaseEntity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>